FROM postgres:14-alpine
COPY explore-with-me-stats/stats-service/src/main/resources/schema.sql /docker-entrypoint-initdb.d/
#COPY explore-wth-me-main/src/main/resources/schema.sql /docker-entrypoint-initdb.d/schema.sql
ENV TZ=Europe/Moscow