DROP TABLE IF EXISTS stats CASCADE;

CREATE TABLE stats (
    id BIGSERIAL PRIMARY KEY,
    app VARCHAR(100) NOT NULL,
    uri VARCHAR(100) NOT NULL,
    ip VARCHAR(100) NOT NULL,
    timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);
